### PR TITLE
Add template for Sorghum Identification - FGVC 9

### PR DESCRIPTION
**Pull request by anlthms**

### CODE REVIEW

**Comment by hornof** [comment]
Lots of stuff working, really cool.  I also think you came up with a way to submit to Kaggle w/o having to copy/paste into a Kaggle notebook?  If so, that could be a really nice improvement.

I did run into a few issues (including submitting to Kaggle).  Details below.

> - Configure your [Kaggle API token](https://github.com/Kaggle/kaggle-api) on the `Import Data` tab.

Done.

> - Attach a Compute Server with a GPU (e.g. gcp-t4).

Done.

> - On the `Import Data` data tab, choose Kaggle and then enter `anlthms/sorghum1` (User Dataset).

Done.

> - For exploratory analysis, run [eda.ipynb](eda.ipynb).

**(see error below)**

> - To train, use the `Run Experiment` menu.

Done.

> - To monitor training progress, use the `Experiment Visualization` menu.

Done.

> - To generate a report on the most recent training session, run report.sh from the `Run Experiment` tab. Make sure `Track Experiment` is checked. The results will be copied back to a file called `report.html`.

**(see error below)**

> - To tune the hyperparameters, edit [sweep.yaml](sweep.yaml) as desired and launch a sweep from the `Run Experiment` tab. Tuned values will be copied back to a file called `config-tuned.yaml` along with visualizations in `sweep-results.html`.

Skipped.

> - After an experiment is complete, use the file browser on the IDE interface to access the results on the IDE Server.

**Not sure what this means.  Results in the output directory? They could also use Experiment Tracking for that.**

> - Use the `Experiment Tracking` menu to track experiments.

Done.

> - Launch inference.sh to create submission.csv and use submit.sh to upload it to Kaggle.

**Maybe add "be sure to check Track Experiment" again.  Also ran into an error while trying to submit it.  (see error below)**

Here's the errors:

1. eda.ipynb:

image

Indeed, that file is not in the input directory.  Variations of that file are, though:

image

2. report.html:

image

3. submit.sh

image

**Comment by hornof** [comment]
> image

It occurred to me that because I downloaded user data this time, I never accepted the rules to that competition.  Once I did that, the submission worked.  Adding a comment/link to the README would be helpful.

image

image

**Comment by hornof** [comment]
Also, I ran a sweep overnight with the default code, i.e. 15 trials per sweep, 60 epochs per trial (but with early stopping if there's no change in 10 epochs).

image

Overall it looks good, but it only ran 10 successful trials.  That last 5 trials all ran out of memory:

> RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 14.76 GiB total capacity; 13.09 GiB already allocated; 22.81 MiB free; 13.14 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by hornof** [comment]
> 1. eda.ipynb:

Fixed.  Notebook working now (with a warning since a ton of images get displayed).

image

**Comment by hornof** [comment]
2. report.sh: Still seeing errors (full output here [report-errors.txt](https://github.com/luminide/luminide-templates/files/8542606/report-errors.txt)).

> RuntimeError: CUDA out of memory. Tried to allocate 120.00 MiB (GPU 0; 15.78 GiB total capacity; 14.21 GiB already allocated; 58.75 MiB free; 14.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by anlthms** [comment]
> report.sh: Still seeing errors (full output here [report-errors.txt](https://github.com/luminide/luminide-templates/files/8542606/report-errors.txt)).

normal if you were training at the same time

**Comment by hornof** [comment]
> > report.sh: Still seeing errors (full output here [report-errors.txt](https://github.com/luminide/luminide-templates/files/8542606/report-errors.txt)).

> normal if you were training at the same time

I wasn't.

**Comment by anlthms** [comment]
I am able to reproduce the OOM issue. good catch!

**Pull request merged**
