### PR TITLE
Template for instance segmentation

### PR DESCRIPTION
**Pull request by anlthms**

### CODE REVIEW

**Comment by anlthms** [comment]
this can be tested on any server (local/dev/staging/hub). a new option called "Instance Segmentation" should show up under code templates.
Screenshot from 2022-03-25 08-54-22

the code is fairly generic, but I have only tested with https://www.kaggle.com/competitions/sartorius-cell-instance-segmentation.

**Comment by hornof** [comment]
> 1. Attach a Compute Server and download a dataset. An example dataset would be `https://www.kaggle.com/c/sartorius-cell-instance-segmentation/data`.

If you want to make it more Luminide specific...

Attach a Compute Server and download a dataset. An example dataset would be `https://www.kaggle.com/c/sartorius-cell-instance-segmentation/data` (in Luminide select Import Data to Compute Server > Kaggle > Competition and enter "sartorius-cell-instance-segmentation" after first accepting the rules).

> 2. Run Experiment custom script

Ran on staging.  Got this error:  ModuleNotFoundError: No module named 'detectron2'

I ran the following two commands to install it (from  https://detectron2.readthedocs.io/en/latest/tutorials/install.html)
```
  python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
  python -m pip install -e detectron2
```

My torch/detectron versions:
torch	1.9.1
detectron2              0.6

> 3. [eda.ipynb]

Looks good.

image

> 4. Run Experiment

Looks good.  FYI, output pretty verbose.

> 5. Visualization

Lots of data.  Looks cool.  Seems good, but to be honest I'm not exactly sure what to look at... 

image
image

> 6. To use this repo for a Kaggle code competition:
>     - Configure your [Kaggle API token](https://github.com/Kaggle/kaggle-api) on the `Import Data` tab.

Skipped.

> 7. Run [kaggle.sh](kaggle.sh) as a custom experiment to upload the code to Kaggle.

Run [kaggle.sh](kaggle.sh) from the `Run Experiment > Custom` tab to upload the code to Kaggle.

>   8.  To create a submission, copy [kaggle.ipynb](kaggle.ipynb) to a new Kaggle notebook.

Good.

>   9.   Add the notebook output of `https://www.kaggle.com/luminide/wheels2` as Data.
>       Add your dataset at `https://www.kaggle.com/<kaggle_username>/kagglecode` as Data.
>       Add the relevant competition dataset as Data.

Good. 

>    10. Run the notebook after turning off the `Internet` setting.

Run the notebook after selecting a GPU `Accelerator` and  turning off the `Internet` setting.

Ran it and it worked just fine.  Wasn't obvious to me when it was finished (e.g. no "Done" message).  But guessing most Kaggle users know when it's done.

FWIW, I tried submitting but due to high capacity, got put in a queue.  Not sure if you want me to check that as well... but will let you know if I see any issues there.

**Comment by anlthms** [comment]
sounds good. I will add your suggestion about data import to the README.
if you get a chance, also try report.sh and a fast sweep - just to make sure they complete without errors.

**Comment by hornof** [comment]
> report.sh 

Fails with the following log file.  Not clear what the issue is.

[error-file.txt](https://github.com/luminide/luminide-templates/files/8354055/error-file.txt)

When I ran the notebook manually, it generated the following error: ../output/history.csv not found

Indeed, that file does not exist in my project.  Maybe because I didn't run the full training to completion (only 8/50 epochs), instead of all the way to the end?

> fast sweep 

Running 10 trials w/ 3 epochs each.  Looks like it's working.  

A bit slow, though.  Trial 0 took 13.0 minutes and just finished, on Trial 1 now.  

Also a bit verbose.  Looks like the bulk of the output is for each trial it's printing the entire model, which is around 570 lines long e.g. 

```
[03/25 22:21:57 d2.engine.defaults]: Model:
GeneralizedRCNN(
  (backbone): FPN(
    (fpn_lateral2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral3): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral4): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral5): Conv2d(2048, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
...
```

**Comment by anlthms** [comment]
> Indeed, that file does not exist in my project. Maybe because I didn't run the full training to completion (only 8/50 epochs), instead of all the way to the end?

yes, we save the history file after training is complete. I will change the code to save after every epoch.

**Comment by hornof** [comment]
Fast sweep finally finished (10 trials of 3 epochs took 122.0 minutes total).

Results look a little weird, but maybe not that bad.  "Best so far" occurred in trials 0, 1, and 9 (which I verified by checking the sweep_results_raw.csv).

image

Also verified history.csv was written (I ran this on staging).  But it was in output/exp7/history.csv (the error above suggested it was looking for it in `../output/history.csv`. -- so not sure it would have found it).

**Comment by anlthms** [comment]
ah... `../output/history.csv` is the correct path on the Compute Server (all notebooks execute there)

**Pull request merged**
