### PR TITLE
Support for sweeps. Conditionals for AMP and augmentation

### PR DESCRIPTION
**Pull request by anlthms**

### CODE REVIEW

**Comment by anlthms** [comment]
this fixes https://github.com/luminide/ide-service/issues/532.

now there is a single template in the repo. AMP and augmentation are supported as conditionals. writing `history.csv` is not a conditional, but included as default. we can revisit if needed.

code generated from the new template should work with the [sweeps prototype](https://github.com/luminide/ide-service/pull/518). note that the code still follows the old convention of having `train.sh` and `trial.sh` in the repo. once we move to defining command lines in the yaml files, we can get rid of the `.sh` files.

**Review by rgharris — APPROVED** [review]
Looks good to me, great to see the duplicated code gone. Tested locally by generating code via cookiecutter's cli, did not run the generated code. 

Should work well to handle `["True", "False"]` via Yes/No radio buttons as a special case when we add support for dropdown options.

**Comment by rgharris** [comment]
> note that the code still follows the old convention of having `train.sh` and `trial.sh` in the repo. once we move to defining command lines in the yaml files, we can get rid of the `.sh` files.

Logged in https://github.com/luminide/ide-service/issues/535


> Should work well to handle `["True", "False"]` via Yes/No radio buttons as a special case when we add support for dropdown options.

Logged in https://github.com/luminide/ide-service/issues/531

**Review by hornof — APPROVED** [review]
Code looks good.

Didn't test because I'm not sure how (change something in ide-service luminide/src/components/code-templates?).  Probably okay, we'll should find/fix anything as we continue developing everything.

**Pull request merged**
