### PR TITLE
Support for multi-label classification and Kaggle integration

### PR DESCRIPTION
**Pull request by anlthms**
Support multilabel classification

Avoid having to specify the number of classes

- Glean the number of classes from the metadata file (no need to
  ask for user input)
- Isolate augmentation code for inference
- Display class names in the EDA notebook
 
Support inference 

- Let test images be loaded from a separate directory
  called test_images

- Also added SGD as an optimizer option
 
Support uploading code to Kaggle 

- Add a script for uploading code and models to a private
  Kaggle dataset
- Add a notebook that can be used for making submissions
  on Kaggle

Miscellaneous

- Document usage of the generated code
- Correct a few linter errors
- Change default hyperparameter values
	- Increase default epochs from 30 to 40
	- Decrease default batch size to 32
	- Slower rate of decay for learning rate
	  (larger gamma)
- More options inside sweep.yaml
- Use ruamel to read config.yaml files

### CODE REVIEW

**Comment by anlthms** [comment]
some names in the dataset (files, columns) are now assumed to match with those in https://www.kaggle.com/c/plant-pathology-2021-fgvc8/data

the data in these buckets have been updated to match with the naming conventions in this code:
 - gs://luminide-example-darkmatter
 - gs://luminide-example-plant-pathology

the branch of this repo that is used in the production code (releases/2) now has the code from this PR (to make it easy to test)

also https://github.com/luminide/example-darkmatter now has code generated from this template (so that the tutorial in its current form is operational)

**Comment by anlthms** [comment]
recommended way to test (on staging):

- push the latest ide-server code to the staging server
- create an empty project and then generate code from template
- accept the default for all options other than "Kaggle". pick True for Kaggle.
- follow the usage instructions in the generated README.md file
    - import data from gs://luminide-example-plant-pathology
    - run eda.ipynb
    - run a training session
    - tune using full sweep
    - upload to kaggle
    - submit entry on kaggle

possible issues:
- ruamel package not installed on compute servers (`pip install ruamel.yaml` as a temporary solution)
- https://github.com/luminide/ide-service/issues/589
- https://github.com/luminide/ide-service/issues/590

TODO:
- making this work with https://www.kaggle.com/c/plant-pathology-2021-fgvc8/data (very slow right now)
- make a notebook for reporting the results instead of just leaving a png file behind
- stretch goal - include class activation maps in the report

**Comment by hornof** [comment]
- Data import was really fast (gs://luminide-example-plant-pathology). Maybe 30 sec or so.  Nice.
  - Modify and run eda.ipynb:
    - At first I thought it was a script I needed to run.  When I realized it was just a notebook, just clicking on it worked.
    - I chose "restart the kernel, then re-run the entire notebook".  Got this error:
       `ModuleNotFoundError: No module named 'util'`
    - I installed ruamel.yaml but that didn't help (good news is that "manage packages" and "pip install" all worked correctly)
    - I didn't modify eda.ipynb.  Not sure how I was supposed to modify it.  Maybe that's the problem?

**Comment by hornof** [comment]
> - To train, use the `Run Experiment` menu.

Worked well.  Assumption is that the user will know to click on the "Start full training" button.

> - To monitor training progress, use the `Experiment Visualization` menu.

Worked well.
image


> - To tune the hyperparameters, edit [sweep.yaml](sweep.yaml) as desired and launch a sweep from the `Run Experiment` tab.

Worked well.  Assumption is that the user knows to click on the Sweep tab and click the "Start full sweep" button.

Sweep was interrupted, presumably by the spot instance getting preempted. Not an issue with the PR, but:
- Error message "Compute detached" was displayed. Good.
- Error message "Code directory empty" was displayed.  Seems like a bug.
- No log files were saved to the Experiment Tracking output directory.   Also looks like a bug.

> - After an experiment is complete, use the file browser on the IDE interface to access the results on the IDE Server.

Looks good.  Verified the sweep results chart matched the TensorBoard output:
image
image

> - Use the `Experiment Tracking` menu to track experiments.

As mentioned, logs for full training looked good.  Logs for sweep were missing (due to spot instance getting preempted).

> - To use this repo for a Kaggle code competition, use [kaggle.sh](kaggle.sh) and [kaggle.ipynb](kaggle.ipynb) to upload and submit the code to Kaggle.

Failed with this message:
```
error: ~/.kaggle/kaggle.json not found on Compute Server
Run Experiment Process Errored 
```
1. Looks like my Kaggle token was missing.  Kind of confusing because I think I didn't need it to download the dataset (got it from a Google bucket), so I hadn't already done that.  Maybe include this in the instructions somewhere. 
2. Is there a typo in the kaggle.sh script?  Should the pathname be "\~/.luminide/kaggle.json" instead of "~/.kaggle/kaggle.json"?  I see the token in that directory on the IDE server -- but it's still missing on the Compute server.

**Comment by anlthms** [comment]
> Looks like my Kaggle token was missing.

yes, that is a known issue - https://github.com/luminide/ide-service/issues/586

**Comment by hornof** [comment]
> ### Using this repo with Luminide
> - Attach a Compute Server and download a dataset. An example dataset is available at gs://luminide-example-plant-pathology.

Good.  (Ran into some Compute Server, rsync, and GUI issues.  But pretty sure all are unrelated to this ticket.  Robert filed separate issues for them).

> - For exploratory analysis, run [eda.ipynb](eda.ipynb).

Good.

> - To train, use the `Run Experiment` menu.

Good.

> - To monitor training progress, use the `Experiment Visualization` menu.

Good.

> - To tune the hyperparameters, edit [sweep.yaml](sweep.yaml) as desired and launch a sweep from the `Run Experiment` tab.

Good.

> - After an experiment is complete, use the file browser on the IDE interface to access the results on the IDE Server.

Good.

> - Use the `Experiment Tracking` menu to track experiments.

Good.

> - To use this repo for a Kaggle code competition:
>     - Configure your [Kaggle API token](https://github.com/Kaggle/kaggle-api) on the `Import Data` tab.

(skipped)

>     - Run [kaggle.sh](kaggle.sh) as a custom experiment to upload the code to Kaggle.

Good.
>     - To create a submission, copy [kaggle.ipynb](kaggle.ipynb) to a new Kaggle notebook and run it.

Worked correctly.  Only issue was that I had to iterate multiple times and fix the error each time.  Might be nicer to add a comment in the README and/or notebook so the user knows to do these things up front (or at least sees that they're required, so they're not surprised if/when they do get an error):
1. Run this on Kaggle after adding the notebook output of https://www.kaggle.com/luminide/wheels as Data
2. Your dataset at https://www.kaggle.com/<kaggle_username>/kagglecode should be added as Data
3. Add the competition dataset
4. Disconnect from the Internet
5. Enable the GPU

Once I did each of these, it looks like it worked.  (I submitted my results 13 minutes ago, and it's still running.  But looks good).

**Comment by hornof** [comment]
Submission succeeded.  0.62914 (private)  and 0.59948 (public) comes in around 450/626.

image

One confusing aspect is that the submission.csv file does contain a row with an empty label.  Not sure why, e.g. is it an error (even healthy leaves should be labeled "healthy"? is it hurting the submission score (seems likely)?  Might be worth investigating.

```
image,labels
85f8cb619c66b863.jpg,
ad8770db05586b59.jpg,complex frog_eye_leaf_spot
c7b03e718489f3ca.jpg,frog_eye_leaf_spot
```

In any case, looks like everything's working.  Nice.

**Comment by anlthms** [comment]
merging... will take care of the issues raised in the next PR.

**Pull request merged**
