### PR TITLE
Semantic segmentation 

### PR DESCRIPTION
**Pull request by anlthms**

### CODE REVIEW

**Comment by anlthms** [comment]
these commits are already on the main branch

**Review by rgharris — APPROVED** [review]
Tested with `main` on hub.luminide.com - looks good! Have not trained yet.

**Comment by anlthms** [comment]
merged into release/2. when you get a chance, train for a couple of epochs and try making a submission - just to make sure that the entire pipeline works.

**Comment by rgharris** [comment]
Worked well for me! I got a score of 0.812 on Kaggle with 2 epochs of training.

**Pull request merged**
